export const cards = [
  { rank: '2', suit: 'hearts', card_value: 2 },
  { rank: '3', suit: 'hearts', card_value: 3 },
  { rank: '4', suit: 'hearts', card_value: 4 },
  { rank: '5', suit: 'hearts', card_value: 5 },
  { rank: '6', suit: 'hearts', card_value: 6 },
  { rank: '7', suit: 'hearts', card_value: 7 },
  { rank: '8', suit: 'hearts', card_value: 8 },
  { rank: '9', suit: 'hearts', card_value: 9 },
  { rank: '10', suit: 'hearts', card_value: 10 },
  { rank: 'J', suit: 'hearts', card_value: 10 },
  { rank: 'Q', suit: 'hearts', card_value: 10 },
  { rank: 'K', suit: 'hearts', card_value: 10 },
  { rank: 'A', suit: 'hearts', card_value: 11 },

  { rank: '2', suit: 'diamonds', card_value: 2 },
  { rank: '3', suit: 'diamonds', card_value: 3 },
  { rank: '4', suit: 'diamonds', card_value: 4 },
  { rank: '5', suit: 'diamonds', card_value: 5 },
  { rank: '6', suit: 'diamonds', card_value: 6 },
  { rank: '7', suit: 'diamonds', card_value: 7 },
  { rank: '8', suit: 'diamonds', card_value: 8 },
  { rank: '9', suit: 'diamonds', card_value: 9 },
  { rank: '10', suit: 'diamonds', card_value: 10 },
  { rank: 'J', suit: 'diamonds', card_value: 10 },
  { rank: 'Q', suit: 'diamonds', card_value: 10 },
  { rank: 'K', suit: 'diamonds', card_value: 10 },
  { rank: 'A', suit: 'diamonds', card_value: 11 },

  { rank: '2', suit: 'clubs', card_value: 2 },
  { rank: '3', suit: 'clubs', card_value: 3 },
  { rank: '4', suit: 'clubs', card_value: 4 },
  { rank: '5', suit: 'clubs', card_value: 5 },
  { rank: '6', suit: 'clubs', card_value: 6 },
  { rank: '7', suit: 'clubs', card_value: 7 },
  { rank: '8', suit: 'clubs', card_value: 8 },
  { rank: '9', suit: 'clubs', card_value: 9 },
  { rank: '10', suit: 'clubs', card_value: 10 },
  { rank: 'J', suit: 'clubs', card_value: 10 },
  { rank: 'Q', suit: 'clubs', card_value: 10 },
  { rank: 'K', suit: 'clubs', card_value: 10 },
  { rank: 'A', suit: 'clubs', card_value: 11 },

  { rank: '2', suit: 'spades', card_value: 2 },
  { rank: '3', suit: 'spades', card_value: 3 },
  { rank: '4', suit: 'spades', card_value: 4 },
  { rank: '5', suit: 'spades', card_value: 5 },
  { rank: '6', suit: 'spades', card_value: 6 },
  { rank: '7', suit: 'spades', card_value: 7 },
  { rank: '8', suit: 'spades', card_value: 8 },
  { rank: '9', suit: 'spades', card_value: 9 },
  { rank: '10', suit: 'spades', card_value: 10 },
  { rank: 'J', suit: 'spades', card_value: 10 },
  { rank: 'Q', suit: 'spades', card_value: 10 },
  { rank: 'K', suit: 'spades', card_value: 10 },
  { rank: 'A', suit: 'spades', card_value: 11 },
];

export const strategyData = [
  // HARD TOTALS
  // Player hand 8
  { players_hand: '8', dealers_upcard: '2', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: '3', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: '4', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: '5', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: '6', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: '7', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: '8', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: '9', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: '10', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '8', dealers_upcard: 'A', recc_action: 'H', hand_type: 'hard' },

  // Player hand 9
  { players_hand: '9', dealers_upcard: '2', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: '3', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: '4', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: '5', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: '6', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: '7', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: '8', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: '9', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: '10', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '9', dealers_upcard: 'A', recc_action: 'H', hand_type: 'hard' },

  // Player hand 10
  { players_hand: '10', dealers_upcard: '2', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: '3', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: '4', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: '5', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: '6', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: '7', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: '8', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: '9', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: '10', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '10', dealers_upcard: 'A', recc_action: 'H', hand_type: 'hard' },

  // Player hand 11
  { players_hand: '11', dealers_upcard: '2', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: '3', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: '4', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: '5', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: '6', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: '7', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: '8', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: '9', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: '10', recc_action: 'D', hand_type: 'hard' },
  { players_hand: '11', dealers_upcard: 'A', recc_action: 'D', hand_type: 'hard' },

  // Player hand 12
  { players_hand: '12', dealers_upcard: '2', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: '3', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: '7', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: '8', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: '9', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: '10', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '12', dealers_upcard: 'A', recc_action: 'H', hand_type: 'hard' },

  // Player hand 13
  { players_hand: '13', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: '7', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: '8', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: '9', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: '10', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '13', dealers_upcard: 'A', recc_action: 'H', hand_type: 'hard' },

  // Player hand 14
  { players_hand: '14', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: '7', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: '8', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: '9', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: '10', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '14', dealers_upcard: 'A', recc_action: 'H', hand_type: 'hard' },

  // Player hand 15
  { players_hand: '15', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: '7', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: '8', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: '9', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: '10', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '15', dealers_upcard: 'A', recc_action: 'H', hand_type: 'hard' },

  // Player hand 16
  { players_hand: '16', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: '7', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: '8', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: '9', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: '10', recc_action: 'H', hand_type: 'hard' },
  { players_hand: '16', dealers_upcard: 'A', recc_action: 'H', hand_type: 'hard' },

  // Player hand 17
  { players_hand: '17', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: '7', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: '8', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: '9', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: '10', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '17', dealers_upcard: 'A', recc_action: 'S', hand_type: 'hard' },

  // Player hands 18-21 (all stand)
  { players_hand: '18', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: '7', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: '8', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: '9', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: '10', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '18', dealers_upcard: 'A', recc_action: 'S', hand_type: 'hard' },

  { players_hand: '19', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: '7', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: '8', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: '9', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: '10', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '19', dealers_upcard: 'A', recc_action: 'S', hand_type: 'hard' },

  { players_hand: '20', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: '7', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: '8', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: '9', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: '10', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '20', dealers_upcard: 'A', recc_action: 'S', hand_type: 'hard' },

  { players_hand: '21', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: '7', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: '8', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: '9', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: '10', recc_action: 'S', hand_type: 'hard' },
  { players_hand: '21', dealers_upcard: 'A', recc_action: 'S', hand_type: 'hard' },

  // SOFT TOTALS
  // Player hand A,2 (soft 13)
  { players_hand: '13', dealers_upcard: '2', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: '3', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: '4', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: '5', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: '6', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: '7', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: '8', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: '9', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: '10', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '13', dealers_upcard: 'A', recc_action: 'H', hand_type: 'soft' },

  // Player hand A,3 (soft 14)
  { players_hand: '14', dealers_upcard: '2', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: '3', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: '4', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: '5', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: '6', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: '7', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: '8', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: '9', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: '10', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '14', dealers_upcard: 'A', recc_action: 'H', hand_type: 'soft' },

  // Player hand A,4 (soft 15)
  { players_hand: '15', dealers_upcard: '2', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: '3', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: '4', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: '5', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: '6', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: '7', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: '8', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: '9', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: '10', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '15', dealers_upcard: 'A', recc_action: 'H', hand_type: 'soft' },

  // Player hand A,5 (soft 16)
  { players_hand: '16', dealers_upcard: '2', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: '3', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: '4', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: '5', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: '6', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: '7', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: '8', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: '9', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: '10', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '16', dealers_upcard: 'A', recc_action: 'H', hand_type: 'soft' },

  // Player hand A,6 (soft 17)
  { players_hand: '17', dealers_upcard: '2', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: '3', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: '4', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: '5', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: '6', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: '7', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: '8', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: '9', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: '10', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '17', dealers_upcard: 'A', recc_action: 'H', hand_type: 'soft' },

  // Player hand A,7 (soft 18)
  { players_hand: '18', dealers_upcard: '2', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: '3', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: '4', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: '5', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: '6', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: '7', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: '8', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: '9', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: '10', recc_action: 'H', hand_type: 'soft' },
  { players_hand: '18', dealers_upcard: 'A', recc_action: 'H', hand_type: 'soft' },

  // Player hand A,8 (soft 19)
  { players_hand: '19', dealers_upcard: '2', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: '3', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: '4', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: '5', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: '6', recc_action: 'D', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: '7', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: '8', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: '9', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: '10', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '19', dealers_upcard: 'A', recc_action: 'S', hand_type: 'soft' },

  // Player hand A,9 (soft 20)
  { players_hand: '20', dealers_upcard: '2', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: '3', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: '4', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: '5', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: '6', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: '7', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: '8', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: '9', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: '10', recc_action: 'S', hand_type: 'soft' },
  { players_hand: '20', dealers_upcard: 'A', recc_action: 'S', hand_type: 'soft' },

  // PAIRS
  // Player hand A,A
  { players_hand: '2', dealers_upcard: '2', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: '3', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: '4', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: '5', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: '6', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: '7', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: '8', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: '9', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: '10', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '2', dealers_upcard: 'A', recc_action: 'P', hand_type: 'pair' },

  // Player hand 2,2
  { players_hand: '4', dealers_upcard: '2', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: '3', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: '4', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: '5', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: '6', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: '7', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: '8', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: '9', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: '10', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '4', dealers_upcard: 'A', recc_action: 'H', hand_type: 'pair' },

  // Player hand 3,3
  { players_hand: '6', dealers_upcard: '2', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: '3', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: '4', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: '5', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: '6', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: '7', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: '8', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: '9', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: '10', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '6', dealers_upcard: 'A', recc_action: 'H', hand_type: 'pair' },

  // Player hand 4,4
  { players_hand: '8', dealers_upcard: '2', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: '3', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: '4', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: '5', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: '6', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: '7', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: '8', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: '9', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: '10', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '8', dealers_upcard: 'A', recc_action: 'H', hand_type: 'pair' },

  // Player hand 5,5 (treat as hard 10 - not split)
  { players_hand: '10', dealers_upcard: '2', recc_action: 'D', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: '3', recc_action: 'D', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: '4', recc_action: 'D', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: '5', recc_action: 'D', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: '6', recc_action: 'D', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: '7', recc_action: 'D', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: '8', recc_action: 'D', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: '9', recc_action: 'D', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: '10', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '10', dealers_upcard: 'A', recc_action: 'H', hand_type: 'pair' },

  // Player hand 6,6
  { players_hand: '12', dealers_upcard: '2', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: '3', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: '4', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: '5', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: '6', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: '7', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: '8', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: '9', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: '10', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '12', dealers_upcard: 'A', recc_action: 'H', hand_type: 'pair' },

  // Player hand 7,7
  { players_hand: '14', dealers_upcard: '2', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: '3', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: '4', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: '5', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: '6', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: '7', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: '8', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: '9', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: '10', recc_action: 'H', hand_type: 'pair' },
  { players_hand: '14', dealers_upcard: 'A', recc_action: 'H', hand_type: 'pair' },

  // Player hand 8,8
  { players_hand: '16', dealers_upcard: '2', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: '3', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: '4', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: '5', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: '6', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: '7', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: '8', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: '9', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: '10', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '16', dealers_upcard: 'A', recc_action: 'P', hand_type: 'pair' },

  // Player hand 9,9
  { players_hand: '18', dealers_upcard: '2', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: '3', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: '4', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: '5', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: '6', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: '7', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: '8', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: '9', recc_action: 'P', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: '10', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '18', dealers_upcard: 'A', recc_action: 'S', hand_type: 'pair' },

  // Player hand 10,10 (treat as hard 20 - never split)
  { players_hand: '20', dealers_upcard: '2', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: '3', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: '4', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: '5', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: '6', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: '7', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: '8', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: '9', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: '10', recc_action: 'S', hand_type: 'pair' },
  { players_hand: '20', dealers_upcard: 'A', recc_action: 'S', hand_type: 'pair' },

  // Player hand 21 (soft)
{ players_hand: '21', dealers_upcard: '2', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: '3', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: '4', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: '5', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: '6', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: '7', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: '8', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: '9', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: '10', recc_action: 'S', hand_type: 'soft' },
{ players_hand: '21', dealers_upcard: 'A', recc_action: 'S', hand_type: 'soft' },

// Player hand 21 (hard)
{ players_hand: '21', dealers_upcard: '2', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: '3', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: '4', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: '5', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: '6', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: '7', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: '8', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: '9', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: '10', recc_action: 'S', hand_type: 'hard' },
{ players_hand: '21', dealers_upcard: 'A', recc_action: 'S', hand_type: 'hard' },
];
